#!/bin/sh

emacs   src/lib/Utilities.f90\
	src/lib/Debugger.f90\
	src/lib/Quicksort.f90\
	src/lib/SparseKit.f90\
	\
	src/solvers/Linear/LinearSolver.f90\
	src/solvers/Linear/Direct/DirectLinearSolver.f90\
	src/solvers/Linear/Direct/Solvers/mklPardiso.f90\
	src/solvers/Linear/Iterative/IterativeLinearSolver.f90\
	src/solvers/Linear/Iterative/Solvers/IterativeLinearSolverMethod.f90\
	\
	src/solvers/Linear/Iterative/Preconditioner/Preconditioner.f90\
	src/solvers/Linear/Iterative/Preconditioner/PreconditionerMethod.f90\
	src/solvers/Linear/Iterative/Preconditioner/UsePreconditioner.f90\
	\
	src/solvers/Linear/Reorder/ReorderSystem.f90\
	src/solvers/Linear/Reorder/ReorderSystemMethod.f90\
	src/solvers/Linear/Reorder/UseReorderSystem.f90\
	\
	src/solvers/NonLinear/NonLinearSolvers.f90\
        src/solvers/NonLinear/NonLinearSolver.f90\
	src/solvers/NonLinear/Method.f90\
	\
	src/integrator/Integrator.f90\
	src/integrator/IntegratorPtr.f90\
	\
	src/property/FortranParser.f90\
	src/property/FortranParserPtr.f90\
	src/property/Property.f90\
	\
	src/node/Point.f90\
	src/node/Dof.f90\
	src/node/Node.f90\
	src/node/NodePtr.f90\
	\
	src/geometry/Geometry.f90\
	src/geometry/Triangle2D3Node.f90\
	src/geometry/Triangle2D6Node.f90\
	src/geometry/Quadrilateral2D4Node.f90\
	src/geometry/Quadrilateral2D8Node.f90\
	\
	src/geometry/GeometryObject.f90\
	src/element/Element.f90\
	src/condition/Condition.f90\
	\
	src/model/Mesh.f90\
	src/model/ProcessInfo.f90\
	src/model/Model.f90\
	\
	src/sources/Source.f90\
	\
	src/Process/Process.f90\
	\
	src/SolvingStrategy/SolvingStrategy.f90\
	src/SolvingStrategy/Scheme.f90\
	src/SolvingStrategy/BuilderAndSolver.f90\
	\
        src/io/IOData.f90&
